kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deployment-reader
rules:
  - verbs: [ "watch", "get", "list" ]
    apiGroups: [ "apps" ]
    resources: [ "deployments" ]
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: deployment-reader
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deployment-reader
roleRef:
  kind: Role
  name: deployment-reader
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: deployment-reader